---
title: "Results"
author: "Erik Ø. Sørensen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(targets)
library(tidyverse)
library(modelsummary)
library(gt)
```

# Reduced form evidence

```{r Regressions of average risk taking, echo=FALSE}
tab5map <- c("treatmentshort"="Treatment short (d)",
             "treatmentlong" ="Treatment long (d)",
             "treatmentnever"="Treatment never (d)",
             "age"="Age (18--92)",
             "genderFemale"="Female (d)",
             "parentTRUE"="Parent (d)",
             "eduHigh school"="High school (d)",
             "eduShort tertiary, e.g. technical college"="Tertiary vocational (d)",
             "eduUniversity level"="Higher education (d)",
             "riskown" = "Own riskwillingness (1--7)",
             "riskothers"="Belief about other's risk willingness (1--7)",
             "good_works"="Own willingness for good works (1--7)",
             "affecthopeful"="Hopeful (d)",
             "affectexcited"="Excited (d)",
             "affectworried"="Worried (d)",
             "affectanxious"="Anxious (d)",
             "(Intercept)"="Constant")


tar_load(average_risk_taking_on_background) 
tab5 <- average_risk_taking_on_background |> 
  modelsummary(coef_map = tab5map, output="gt") |>
  tab_spanner(label="Now", columns=4) |>
  tab_spanner(label="Short", columns=5) |>
  tab_spanner(label="Long", columns=6) |>
  tab_spanner(label="Never", columns=7) |>
  tab_spanner(label="Treatment", columns=4:7) 
tab5
gtsave(tab5, here::here("tables","average_risk_taking_on_background.tex"))
```


# An empirical choice model

The model is defined in the stan file, no empirical results in this sectino.

# Choice model estimates

```{r Loading priors and posteriors, include=FALSE}
tar_load(posterior_draws)
tar_load(prior_densities)
```

## For probability weighting 

Creating prior/posterior graphs.

```{r Posterior alpha and beta dists, echo=FALSE}
preAB <- prior_densities |> 
    filter(str_starts(name, "alpha") | str_starts(name, "beta")) 
postAB <- posterior_draws |> 
  dplyr::select(c("treatment", "replication","name", "value")) |>
  filter(str_starts(name, "alpha") | str_starts(name, "beta")) |>
  pivot_wider(
    id_cols = c("treatment","replication"),
    names_from = name,
    values_from = value
  ) |>
  pivot_longer(
    cols = -c("treatment","replication"),       
    names_to = "name",      
    values_to = "value"    
  ) 
ABdraws_median <- postAB |> group_by(treatment, name) |> summarize(mdn = median(value)) |> separate(name, into = c("pname", "vname"), sep = "_") %>%
  pivot_wider(
    names_from = vname,
    values_from = mdn
  ) |> 
  mutate(value = map2(mu, sigma, ~ rlnorm(100000, meanlog = .x, sdlog = .y))) %>%
  unnest(value) |> 
  group_by(treatment, pname) |> 
  mutate(p95 = quantile(value,0.95)) |>
  filter(value <= p95) |>
  rename(name=pname) |>
  dplyr::select(-c("mu","sigma","p95"))
postAB <- postAB |> bind_rows(ABdraws_median) |> mutate(name = factor(name, levels = c("alpha_mu","alpha_sigma","beta_mu","beta_sigma","alpha","beta")))

x_limits_df <- postAB |> 
  group_by(treatment, name) |>
  summarize(xmin = min(value), xmax = max(value), .groups = "drop")
preAB_limited <- preAB |> 
  inner_join(x_limits_df, by = c("treatment", "name")) |>
  filter(value >= xmin, value <= xmax)
pAB <- postAB |> ggplot(aes(x=value)) +
  geom_histogram(  aes(x = value, y = (..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]) , bins=30) +
  geom_line(
    data = preAB_limited,
    aes(x = value, y = 0.2*density),
    color = "red",
    linetype = "dashed",
    size = 1
  ) +
  theme_minimal() +
  facet_grid(treatment ~ name, scales = "free_x") +
  labs(x ="Parameter value", y = "Proportion") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 3))
pAB
ggsave(here::here("graphs","posteriors_AB.pdf"), width=22, height = 16, units = "cm")
```

## Looking at the Prelec function

# Looking at the Prelec functions

```{r Weighting functions, echo=FALSE}
plotdf <- posterior_draws |>
  filter(treatment=="Short") |>
  pivot_wider(id_cols = "replication", names_from="name", values_from = value) |>
  mutate(median_alpha_mu = median(alpha_mu),
            median_alpha_sigma = median(alpha_sigma),
            median_beta_mu = median(beta_mu),
            median_beta_sigma = median(beta_sigma)) |>
  sample_n(500) |>
  transmute(alpha = exp(rnorm(n(),median_alpha_mu,median_alpha_sigma)),
            beta  = exp(rnorm(n(),median_beta_mu,median_beta_sigma)),
            i = row_number()) |> 
  full_join( as_tibble( expand.grid(i=1:500, p = seq(0,1,0.01)))) |>
  mutate(w = exp( - beta * (( - log(p))^alpha)))
weighting_functions <- plotdf |> 
  ggplot(aes(x=p, y=w) ) + 
  geom_line(aes(group=i), size=1/2, alpha=0.2) + 
  stat_function(fun = function(x) x, size=2) +  
  stat_function(fun = function(x) exp( - median(plotdf$beta)*(( - log(x))^median(plotdf$alpha))),
                size=3, color="red") + 
  theme_minimal() +
  scale_x_continuous(breaks=c(0,0.17, 0.33, 0.50, 0.67, 0.83, 1)) +
  theme_bw() + xlab("Probability") + ylab("Probability weight (treatment \"Short\")")
weighting_functions
ggsave(here::here("graphs","weighting_functions.pdf"), width=16, height = 10, units="cm")
```




## For risk aversion and random utility

```{r Posterior lambda and rho dists, echo=FALSE}
preLR <- prior_densities |> 
    filter(str_starts(name, "rho") | str_starts(name, "lambda")) 

postLR <- posterior_draws |> 
  dplyr::select(c("treatment", "replication","name", "value")) |>
  filter(str_starts(name, "lambda") | str_starts(name, "rho")) |>
  pivot_wider(
    id_cols = c("treatment","replication"),
    names_from = name,
    values_from = value
  ) |>
  pivot_longer(
    cols = -c("treatment","replication"),       
    names_to = "name",      
    values_to = "value"    
  ) 
LRdraws_median <- postLR |> group_by(treatment, name) |> summarize(mdn = median(value)) |> separate(name, into = c("pname", "vname"), sep = "_") %>%
  pivot_wider(
    names_from = vname,
    values_from = mdn
  ) |> 
  mutate(value = map2(mu, sigma, ~ rlnorm(100000, meanlog = .x, sdlog = .y))) %>%
  unnest(value) |> 
  group_by(treatment, pname) |> 
  mutate(p95 = quantile(value,0.95)) |>
  filter(value <= p95) |>
  rename(name=pname) |>
  dplyr::select(-c("mu","sigma","p95"))
postLR <- postLR |> bind_rows(LRdraws_median) |> mutate(name = factor(name, levels = c("lambda_mu","lambda_sigma","rho_mu","rho_sigma","lambda","rho")))



x_limits_df <- postLR |>
  group_by(treatment, name) |>
  summarize(xmin = min(value), xmax = max(value), .groups = "drop")
preLR_limited <- preLR |>
  inner_join(x_limits_df, by = c("treatment", "name")) |>
  filter(value >= xmin, value <= xmax)
pLR <- postLR |> ggplot(aes(x=value)) +
  geom_histogram(  aes(x = value, y = (..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]) , bins=30) +
  geom_line(
    data = preLR_limited,
    aes(x = value, y = 0.2*density),
    color = "red",
    linetype = "dashed",
    size = 1
  ) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 3)) +
  theme_minimal() +
  facet_grid(treatment ~ name, scales = "free_x") +
  labs(x ="Parameter value", y = "Proportion") 
pLR
ggsave(here::here("graphs","posteriors_RL.pdf"), width=22, height = 16, units = "cm")
```

